// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package auditdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Website     *string            `json:"website"`
	Industry    *string            `json:"industry"`
	Phone       *string            `json:"phone"`
	Notes       *string            `json:"notes"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Activity struct {
	ID              pgtype.UUID        `json:"id"`
	Body            *string            `json:"body"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	DealID          pgtype.UUID        `json:"deal_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	OrgID           pgtype.UUID        `json:"org_id"`
	Kind            string             `json:"kind"`
	LeadID          pgtype.UUID        `json:"lead_id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	QuoteID         pgtype.UUID        `json:"quote_id"`
	InvoiceID       pgtype.UUID        `json:"invoice_id"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Subject         *string            `json:"subject"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
	DurationMinutes *int32             `json:"duration_minutes"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	IpAddress  *string            `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CalendarEvent struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	GoogleEventID *string            `json:"google_event_id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	MeetLink      *string            `json:"meet_link"`
	LeadID        pgtype.UUID        `json:"lead_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Contact struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  *string            `json:"last_name"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	OrgID     pgtype.UUID        `json:"org_id"`
}

type Deal struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Amount            pgtype.Numeric     `json:"amount"`
	Stage             string             `json:"stage"`
	AccountID         pgtype.UUID        `json:"account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	OrgID             pgtype.UUID        `json:"org_id"`
	Description       *string            `json:"description"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          float64            `json:"position"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Probability       *int32             `json:"probability"`
	ExpectedRevenue   pgtype.Numeric     `json:"expected_revenue"`
	LostReason        *string            `json:"lost_reason"`
	SiteAssessment    []byte             `json:"site_assessment"`
}

type FollowUp struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	Title       string             `json:"title"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	LeadID      pgtype.UUID        `json:"lead_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IntegrationConnection struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	Provider        string             `json:"provider"`
	EncryptedTokens []byte             `json:"encrypted_tokens"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Number        string             `json:"number"`
	Title         *string            `json:"title"`
	Status        string             `json:"status"`
	QuoteID       pgtype.UUID        `json:"quote_id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	ContactID     pgtype.UUID        `json:"contact_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	OwnerUserID   pgtype.UUID        `json:"owner_user_id"`
	Currency      string             `json:"currency"`
	Notes         *string            `json:"notes"`
	IssueDate     pgtype.Date        `json:"issue_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	DiscountTotal pgtype.Numeric     `json:"discount_total"`
	TaxTotal      pgtype.Numeric     `json:"tax_total"`
	Total         pgtype.Numeric     `json:"total"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	VoidedAt      pgtype.Timestamptz `json:"voided_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CgstAmount    pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount    pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount    pgtype.Numeric     `json:"igst_amount"`
	IsInterstate  bool               `json:"is_interstate"`
}

type InvoiceItem struct {
	ID              pgtype.UUID    `json:"id"`
	InvoiceID       pgtype.UUID    `json:"invoice_id"`
	OrgID           pgtype.UUID    `json:"org_id"`
	Position        int32          `json:"position"`
	Description     string         `json:"description"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	DiscountPercent pgtype.Numeric `json:"discount_percent"`
	TaxPercent      pgtype.Numeric `json:"tax_percent"`
	LineTotal       pgtype.Numeric `json:"line_total"`
	ProductID       pgtype.UUID    `json:"product_id"`
}

type Lead struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	FirstName          string             `json:"first_name"`
	LastName           *string            `json:"last_name"`
	Email              *string            `json:"email"`
	Phone              *string            `json:"phone"`
	Company            *string            `json:"company"`
	Source             *string            `json:"source"`
	Notes              *string            `json:"notes"`
	Value              pgtype.Numeric     `json:"value"`
	Stage              string             `json:"stage"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ConvertedAt        pgtype.Timestamptz `json:"converted_at"`
	ConvertedDealID    pgtype.UUID        `json:"converted_deal_id"`
	ConvertedContactID pgtype.UUID        `json:"converted_contact_id"`
	Title              *string            `json:"title"`
	LinkedinUrl        *string            `json:"linkedin_url"`
	ContactID          pgtype.UUID        `json:"contact_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	FollowUpAt         pgtype.Date        `json:"follow_up_at"`
}

type Organization struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Currency   string             `json:"currency"`
	QuoteSeq   int32              `json:"quote_seq"`
	InvoiceSeq int32              `json:"invoice_seq"`
}

type Payment struct {
	ID        pgtype.UUID        `json:"id"`
	InvoiceID pgtype.UUID        `json:"invoice_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Amount    pgtype.Numeric     `json:"amount"`
	PaidOn    pgtype.Date        `json:"paid_on"`
	Method    *string            `json:"method"`
	Reference *string            `json:"reference"`
	Note      *string            `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Sku         string             `json:"sku"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	TaxRate     pgtype.Numeric     `json:"tax_rate"`
	Category    *string            `json:"category"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Quote struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Number        string             `json:"number"`
	Title         *string            `json:"title"`
	Status        string             `json:"status"`
	AccountID     pgtype.UUID        `json:"account_id"`
	ContactID     pgtype.UUID        `json:"contact_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	OwnerUserID   pgtype.UUID        `json:"owner_user_id"`
	Currency      string             `json:"currency"`
	Notes         *string            `json:"notes"`
	ValidUntil    pgtype.Date        `json:"valid_until"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	DiscountTotal pgtype.Numeric     `json:"discount_total"`
	TaxTotal      pgtype.Numeric     `json:"tax_total"`
	Total         pgtype.Numeric     `json:"total"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	AcceptedAt    pgtype.Timestamptz `json:"accepted_at"`
	DeclinedAt    pgtype.Timestamptz `json:"declined_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type QuoteApproval struct {
	ID          pgtype.UUID        `json:"id"`
	QuoteID     pgtype.UUID        `json:"quote_id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	ApproverID  pgtype.UUID        `json:"approver_id"`
	Status      string             `json:"status"`
	DiscountPct pgtype.Numeric     `json:"discount_pct"`
	Notes       *string            `json:"notes"`
	ActionedAt  pgtype.Timestamptz `json:"actioned_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type QuoteItem struct {
	ID              pgtype.UUID    `json:"id"`
	QuoteID         pgtype.UUID    `json:"quote_id"`
	OrgID           pgtype.UUID    `json:"org_id"`
	Position        int32          `json:"position"`
	Description     string         `json:"description"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	DiscountPercent pgtype.Numeric `json:"discount_percent"`
	TaxPercent      pgtype.Numeric `json:"tax_percent"`
	LineTotal       pgtype.Numeric `json:"line_total"`
	ProductID       pgtype.UUID    `json:"product_id"`
}

type QuoteVersion struct {
	ID        pgtype.UUID        `json:"id"`
	QuoteID   pgtype.UUID        `json:"quote_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Version   int32              `json:"version"`
	Snapshot  []byte             `json:"snapshot"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type SlackChannel struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	ChannelID  string             `json:"channel_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   *string            `json:"password_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AuthProvider   string             `json:"auth_provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Name           *string            `json:"name"`
}
