// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    org_id, user_id, action, entity_type, entity_id, changes, ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, org_id, user_id, actor_id, action, entity_type, entity_id, ip_address, before, after, changes, created_at
`

type CreateAuditLogParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Changes    []byte      `json:"changes"`
	IpAddress  *string     `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.OrgID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.IpAddress,
		&i.Before,
		&i.After,
		&i.Changes,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.org_id, a.user_id, a.actor_id, a.action, a.entity_type, a.entity_id, a.ip_address, a.before, a.after, a.changes, a.created_at, u.name AS user_name, u.email AS user_email
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE a.org_id = $1
  AND ($2::text IS NULL OR a.entity_type = $2)
  AND ($3::uuid IS NULL OR a.entity_id = $3)
ORDER BY a.created_at DESC
LIMIT $5 OFFSET $4
`

type ListAuditLogsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	EntityType *string     `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

type ListAuditLogsRow struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	IpAddress  *string            `json:"ip_address"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Changes    []byte             `json:"changes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   *string            `json:"user_name"`
	UserEmail  *string            `json:"user_email"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrgID,
		arg.EntityType,
		arg.EntityID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.IpAddress,
			&i.Before,
			&i.After,
			&i.Changes,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
