// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package followupsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (
    org_id, google_event_id, title, description, start_at, end_at, meet_link, lead_id, deal_id, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, google_event_id, title, description, start_at, end_at, meet_link, lead_id, deal_id, created_by, created_at
`

type CreateCalendarEventParams struct {
	OrgID         pgtype.UUID        `json:"org_id"`
	GoogleEventID *string            `json:"google_event_id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	MeetLink      *string            `json:"meet_link"`
	LeadID        pgtype.UUID        `json:"lead_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRow(ctx, createCalendarEvent,
		arg.OrgID,
		arg.GoogleEventID,
		arg.Title,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.MeetLink,
		arg.LeadID,
		arg.DealID,
		arg.CreatedBy,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.GoogleEventID,
		&i.Title,
		&i.Description,
		&i.StartAt,
		&i.EndAt,
		&i.MeetLink,
		&i.LeadID,
		&i.DealID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createFollowUp = `-- name: CreateFollowUp :one
INSERT INTO follow_ups (
    org_id, assigned_to, title, due_at, lead_id, deal_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, org_id, assigned_to, title, due_at, completed_at, lead_id, deal_id, created_at
`

type CreateFollowUpParams struct {
	OrgID      pgtype.UUID        `json:"org_id"`
	AssignedTo pgtype.UUID        `json:"assigned_to"`
	Title      string             `json:"title"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	LeadID     pgtype.UUID        `json:"lead_id"`
	DealID     pgtype.UUID        `json:"deal_id"`
}

func (q *Queries) CreateFollowUp(ctx context.Context, arg CreateFollowUpParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, createFollowUp,
		arg.OrgID,
		arg.AssignedTo,
		arg.Title,
		arg.DueAt,
		arg.LeadID,
		arg.DealID,
	)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssignedTo,
		&i.Title,
		&i.DueAt,
		&i.CompletedAt,
		&i.LeadID,
		&i.DealID,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendarEvents = `-- name: ListCalendarEvents :many
SELECT id, org_id, google_event_id, title, description, start_at, end_at, meet_link, lead_id, deal_id, created_by, created_at FROM calendar_events
WHERE org_id = $1
  AND start_at >= $2 AND end_at <= $3
ORDER BY start_at ASC
`

type ListCalendarEventsParams struct {
	OrgID   pgtype.UUID        `json:"org_id"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
}

func (q *Queries) ListCalendarEvents(ctx context.Context, arg ListCalendarEventsParams) ([]CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listCalendarEvents, arg.OrgID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.GoogleEventID,
			&i.Title,
			&i.Description,
			&i.StartAt,
			&i.EndAt,
			&i.MeetLink,
			&i.LeadID,
			&i.DealID,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowUps = `-- name: ListFollowUps :many
SELECT id, org_id, assigned_to, title, due_at, completed_at, lead_id, deal_id, created_at FROM follow_ups
WHERE org_id = $1
  AND ($2::uuid IS NULL OR assigned_to = $2)
  AND ($3::boolean IS NULL OR (completed_at IS NOT NULL) = $3)
ORDER BY due_at ASC
`

type ListFollowUpsParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
	Completed  *bool       `json:"completed"`
}

func (q *Queries) ListFollowUps(ctx context.Context, arg ListFollowUpsParams) ([]FollowUp, error) {
	rows, err := q.db.Query(ctx, listFollowUps, arg.OrgID, arg.AssignedTo, arg.Completed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowUp
	for rows.Next() {
		var i FollowUp
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AssignedTo,
			&i.Title,
			&i.DueAt,
			&i.CompletedAt,
			&i.LeadID,
			&i.DealID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFollowUpCompleted = `-- name: MarkFollowUpCompleted :one
UPDATE follow_ups
SET completed_at = now()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, assigned_to, title, due_at, completed_at, lead_id, deal_id, created_at
`

type MarkFollowUpCompletedParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) MarkFollowUpCompleted(ctx context.Context, arg MarkFollowUpCompletedParams) (FollowUp, error) {
	row := q.db.QueryRow(ctx, markFollowUpCompleted, arg.OrgID, arg.ID)
	var i FollowUp
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AssignedTo,
		&i.Title,
		&i.DueAt,
		&i.CompletedAt,
		&i.LeadID,
		&i.DealID,
		&i.CreatedAt,
	)
	return i, err
}
