-- The activity log: the spine the redesign hangs off.
--
-- "Stalled 7+ days", "days idle", "last activity", Company health and the
-- dashboard's needs-attention queue are all questions about *when something last
-- happened*, which nothing in the system could answer before this.
--
-- The table existed from the original scaffold (type/body/contact_id/deal_id) but
-- nothing ever wrote to it. It is empty, so this reshapes it in place.

-- What kind of thing happened. 'system' is generated by the app on a state
-- change; everything else is a human logging something they did.
ALTER TABLE activities
    ADD COLUMN kind TEXT NOT NULL DEFAULT 'note'
    CHECK (kind IN ('note', 'call', 'email', 'meeting', 'site_visit', 'system'));

-- The original scaffold's free-text `type` is replaced by `kind` above.
ALTER TABLE activities DROP COLUMN IF EXISTS type;

-- Every entity an activity can hang off. All nullable: an activity usually names
-- one or two of these (a call with a contact, about a deal).
ALTER TABLE activities ADD COLUMN lead_id    UUID REFERENCES leads(id)    ON DELETE CASCADE;
ALTER TABLE activities ADD COLUMN account_id UUID REFERENCES accounts(id) ON DELETE CASCADE;
ALTER TABLE activities ADD COLUMN quote_id   UUID REFERENCES quotes(id)   ON DELETE CASCADE;
ALTER TABLE activities ADD COLUMN invoice_id UUID REFERENCES invoices(id) ON DELETE CASCADE;

-- Who did it. NULL for system events, and SET NULL if the user is removed —
-- losing a person must not erase the history of what happened.
ALTER TABLE activities ADD COLUMN created_by UUID REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE activities ADD COLUMN subject TEXT;
-- When it actually happened, which is not always when it was typed in: a call is
-- often logged the next morning. Ordering and staleness use this, not created_at.
ALTER TABLE activities ADD COLUMN occurred_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE activities ADD COLUMN duration_minutes INTEGER CHECK (duration_minutes >= 0);

-- Timeline reads: newest first, for one entity.
CREATE INDEX activities_org_occurred_idx ON activities (org_id, occurred_at DESC, id);
CREATE INDEX activities_lead_idx    ON activities (lead_id, occurred_at DESC) WHERE lead_id IS NOT NULL;
CREATE INDEX activities_deal_idx    ON activities (deal_id, occurred_at DESC) WHERE deal_id IS NOT NULL;
CREATE INDEX activities_account_idx ON activities (account_id, occurred_at DESC) WHERE account_id IS NOT NULL;
CREATE INDEX activities_contact_idx ON activities (contact_id, occurred_at DESC) WHERE contact_id IS NOT NULL;

-- Staleness scans ("deals with nothing logged in 7+ days") only ever care about
-- what a human did — a system event recording the very move you are asking about
-- would make every stalled deal look active.
CREATE INDEX activities_org_human_idx
    ON activities (org_id, deal_id, occurred_at DESC)
    WHERE kind <> 'system';
