// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package contactsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountInOrg = `-- name: AccountInOrg :one
SELECT EXISTS (SELECT 1 FROM accounts WHERE org_id = $1 AND id = $2)
`

type AccountInOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

// Guards a contact's account_id: the FK alone would accept another tenant's account.
func (q *Queries) AccountInOrg(ctx context.Context, arg AccountInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountInOrg, arg.OrgID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countContacts = `-- name: CountContacts :one
SELECT count(*) FROM contacts WHERE org_id = $1
`

func (q *Queries) CountContacts(ctx context.Context, orgID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContacts, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (org_id, first_name, last_name, email, phone, account_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, first_name, last_name, email, phone, account_id, created_at
`

type CreateContactParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	FirstName string      `json:"first_name"`
	LastName  *string     `json:"last_name"`
	Email     *string     `json:"email"`
	Phone     *string     `json:"phone"`
	AccountID pgtype.UUID `json:"account_id"`
}

type CreateContactRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  *string            `json:"last_name"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (CreateContactRow, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.OrgID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.AccountID,
	)
	var i CreateContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :execrows
DELETE FROM contacts WHERE org_id = $1 AND id = $2
`

type DeleteContactParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContact, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getContact = `-- name: GetContact :one
SELECT id, first_name, last_name, email, phone, account_id, created_at
FROM contacts
WHERE org_id = $1 AND id = $2
`

type GetContactParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetContactRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  *string            `json:"last_name"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (GetContactRow, error) {
	row := q.db.QueryRow(ctx, getContact, arg.OrgID, arg.ID)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many

SELECT id, first_name, last_name, email, phone, account_id, created_at
FROM contacts
WHERE org_id = $1
ORDER BY created_at DESC, id
LIMIT $2 OFFSET $3
`

type ListContactsParams struct {
	OrgID  pgtype.UUID `json:"org_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListContactsRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  *string            `json:"last_name"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// SQL reference for the eventual sqlc migration; the module currently runs the
// hand-written pgx repository in store.go. Keep the two in sync.
//
// Every statement filters on org_id. A query here without it is a tenant-data
// leak, not a missing filter.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.AccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET first_name = $3, last_name = $4, email = $5, phone = $6, account_id = $7
WHERE org_id = $1 AND id = $2
RETURNING id, first_name, last_name, email, phone, account_id, created_at
`

type UpdateContactParams struct {
	OrgID     pgtype.UUID `json:"org_id"`
	ID        pgtype.UUID `json:"id"`
	FirstName string      `json:"first_name"`
	LastName  *string     `json:"last_name"`
	Email     *string     `json:"email"`
	Phone     *string     `json:"phone"`
	AccountID pgtype.UUID `json:"account_id"`
}

type UpdateContactRow struct {
	ID        pgtype.UUID        `json:"id"`
	FirstName string             `json:"first_name"`
	LastName  *string            `json:"last_name"`
	Email     *string            `json:"email"`
	Phone     *string            `json:"phone"`
	AccountID pgtype.UUID        `json:"account_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (UpdateContactRow, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.OrgID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.AccountID,
	)
	var i UpdateContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}
