// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package dealsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeal = `-- name: CreateDeal :one
INSERT INTO deals (org_id, title, description, amount, stage, owner_user_id,
                   contact_id, expected_close_date, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        COALESCE((SELECT max(position) + 1000 FROM deals WHERE org_id = $1 AND stage = $5), 0))
RETURNING id
`

type CreateDealParams struct {
	OrgID             pgtype.UUID    `json:"org_id"`
	Title             string         `json:"title"`
	Description       *string        `json:"description"`
	Amount            pgtype.Numeric `json:"amount"`
	Stage             string         `json:"stage"`
	OwnerUserID       pgtype.UUID    `json:"owner_user_id"`
	ContactID         pgtype.UUID    `json:"contact_id"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
}

func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.OrgID,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.Stage,
		arg.OwnerUserID,
		arg.ContactID,
		arg.ExpectedCloseDate,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const dealStageOrder = `-- name: DealStageOrder :many
SELECT id FROM deals
WHERE org_id = $1 AND stage = $2 AND id <> $3
ORDER BY position, id
`

type DealStageOrderParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Stage string      `json:"stage"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DealStageOrder(ctx context.Context, arg DealStageOrderParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, dealStageOrder, arg.OrgID, arg.Stage, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dealStats = `-- name: DealStats :many
SELECT stage, count(*), COALESCE(sum(amount), 0)::float8
FROM deals WHERE org_id = $1 GROUP BY stage
`

type DealStatsRow struct {
	Stage   string  `json:"stage"`
	Count   int64   `json:"count"`
	Column3 float64 `json:"column_3"`
}

func (q *Queries) DealStats(ctx context.Context, orgID pgtype.UUID) ([]DealStatsRow, error) {
	rows, err := q.db.Query(ctx, dealStats, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DealStatsRow
	for rows.Next() {
		var i DealStatsRow
		if err := rows.Scan(&i.Stage, &i.Count, &i.Column3); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDeal = `-- name: DeleteDeal :execrows
DELETE FROM deals WHERE org_id = $1 AND id = $2
`

type DeleteDealParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteDeal(ctx context.Context, arg DeleteDealParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeal, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeal = `-- name: GetDeal :one
SELECT d.id, d.title, d.amount, d.stage, d.account_id, d.created_at, d.org_id, d.description, d.owner_user_id, d.contact_id, d.expected_close_date, d.position, d.updated_at, d.probability, d.expected_revenue, d.lost_reason, d.site_assessment, u.name AS owner_name, u.email AS owner_email,
       NULLIF(concat_ws(' ', c.first_name, c.last_name), '') AS contact_name
FROM deals d
LEFT JOIN users u ON u.id = d.owner_user_id
LEFT JOIN contacts c ON c.id = d.contact_id
WHERE d.org_id = $1 AND d.id = $2
`

type GetDealParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetDealRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Amount            pgtype.Numeric     `json:"amount"`
	Stage             string             `json:"stage"`
	AccountID         pgtype.UUID        `json:"account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	OrgID             pgtype.UUID        `json:"org_id"`
	Description       *string            `json:"description"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          float64            `json:"position"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Probability       *int32             `json:"probability"`
	ExpectedRevenue   pgtype.Numeric     `json:"expected_revenue"`
	LostReason        *string            `json:"lost_reason"`
	SiteAssessment    []byte             `json:"site_assessment"`
	OwnerName         *string            `json:"owner_name"`
	OwnerEmail        *string            `json:"owner_email"`
	ContactName       bool               `json:"contact_name"`
}

func (q *Queries) GetDeal(ctx context.Context, arg GetDealParams) (GetDealRow, error) {
	row := q.db.QueryRow(ctx, getDeal, arg.OrgID, arg.ID)
	var i GetDealRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Stage,
		&i.AccountID,
		&i.CreatedAt,
		&i.OrgID,
		&i.Description,
		&i.OwnerUserID,
		&i.ContactID,
		&i.ExpectedCloseDate,
		&i.Position,
		&i.UpdatedAt,
		&i.Probability,
		&i.ExpectedRevenue,
		&i.LostReason,
		&i.SiteAssessment,
		&i.OwnerName,
		&i.OwnerEmail,
		&i.ContactName,
	)
	return i, err
}

const listDealsBoard = `-- name: ListDealsBoard :many

SELECT d.id, d.title, d.amount, d.stage, d.account_id, d.created_at, d.org_id, d.description, d.owner_user_id, d.contact_id, d.expected_close_date, d.position, d.updated_at, d.probability, d.expected_revenue, d.lost_reason, d.site_assessment, u.name AS owner_name, u.email AS owner_email,
       NULLIF(concat_ws(' ', c.first_name, c.last_name), '') AS contact_name
FROM deals d
LEFT JOIN users u ON u.id = d.owner_user_id
LEFT JOIN contacts c ON c.id = d.contact_id
WHERE d.org_id = $1
ORDER BY d.stage, d.position, d.id
LIMIT $2
`

type ListDealsBoardParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Limit int32       `json:"limit"`
}

type ListDealsBoardRow struct {
	ID                pgtype.UUID        `json:"id"`
	Title             string             `json:"title"`
	Amount            pgtype.Numeric     `json:"amount"`
	Stage             string             `json:"stage"`
	AccountID         pgtype.UUID        `json:"account_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	OrgID             pgtype.UUID        `json:"org_id"`
	Description       *string            `json:"description"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          float64            `json:"position"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Probability       *int32             `json:"probability"`
	ExpectedRevenue   pgtype.Numeric     `json:"expected_revenue"`
	LostReason        *string            `json:"lost_reason"`
	SiteAssessment    []byte             `json:"site_assessment"`
	OwnerName         *string            `json:"owner_name"`
	OwnerEmail        *string            `json:"owner_email"`
	ContactName       bool               `json:"contact_name"`
}

// SQL queries for deals package.
// Every statement filters on org_id.
func (q *Queries) ListDealsBoard(ctx context.Context, arg ListDealsBoardParams) ([]ListDealsBoardRow, error) {
	rows, err := q.db.Query(ctx, listDealsBoard, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDealsBoardRow
	for rows.Next() {
		var i ListDealsBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Stage,
			&i.AccountID,
			&i.CreatedAt,
			&i.OrgID,
			&i.Description,
			&i.OwnerUserID,
			&i.ContactID,
			&i.ExpectedCloseDate,
			&i.Position,
			&i.UpdatedAt,
			&i.Probability,
			&i.ExpectedRevenue,
			&i.LostReason,
			&i.SiteAssessment,
			&i.OwnerName,
			&i.OwnerEmail,
			&i.ContactName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refInOrg = `-- name: RefInOrg :one
SELECT EXISTS (SELECT 1 FROM users WHERE org_id = $1 AND id = $2)
`

type RefInOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) RefInOrg(ctx context.Context, arg RefInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, refInOrg, arg.OrgID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reorderDealStage = `-- name: ReorderDealStage :exec
UPDATE deals SET position = v.pos
FROM (
  SELECT unnest($2::uuid[]) AS id, unnest($3::float8[]) AS pos
) v
WHERE deals.id = v.id AND deals.org_id = $1
`

type ReorderDealStageParams struct {
	OrgID   pgtype.UUID   `json:"org_id"`
	Column2 []pgtype.UUID `json:"column_2"`
	Column3 []float64     `json:"column_3"`
}

func (q *Queries) ReorderDealStage(ctx context.Context, arg ReorderDealStageParams) error {
	_, err := q.db.Exec(ctx, reorderDealStage, arg.OrgID, arg.Column2, arg.Column3)
	return err
}

const setDealStage = `-- name: SetDealStage :execrows
UPDATE deals SET stage = $3, updated_at = now() WHERE org_id = $1 AND id = $2
`

type SetDealStageParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
	Stage string      `json:"stage"`
}

func (q *Queries) SetDealStage(ctx context.Context, arg SetDealStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDealStage, arg.OrgID, arg.ID, arg.Stage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeal = `-- name: UpdateDeal :execrows
UPDATE deals
SET title = $3, description = $4, amount = $5, stage = $6,
    owner_user_id = $7, contact_id = $8, expected_close_date = $9,
    updated_at = now()
WHERE org_id = $1 AND id = $2
`

type UpdateDealParams struct {
	OrgID             pgtype.UUID    `json:"org_id"`
	ID                pgtype.UUID    `json:"id"`
	Title             string         `json:"title"`
	Description       *string        `json:"description"`
	Amount            pgtype.Numeric `json:"amount"`
	Stage             string         `json:"stage"`
	OwnerUserID       pgtype.UUID    `json:"owner_user_id"`
	ContactID         pgtype.UUID    `json:"contact_id"`
	ExpectedCloseDate pgtype.Date    `json:"expected_close_date"`
}

func (q *Queries) UpdateDeal(ctx context.Context, arg UpdateDealParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDeal,
		arg.OrgID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.Stage,
		arg.OwnerUserID,
		arg.ContactID,
		arg.ExpectedCloseDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
