// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package productsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    org_id, sku, name, description, unit_price, tax_rate, category, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, org_id, sku, name, description, unit_price, tax_rate, category, is_active, created_at, updated_at
`

type CreateProductParams struct {
	OrgID       pgtype.UUID    `json:"org_id"`
	Sku         string         `json:"sku"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	TaxRate     pgtype.Numeric `json:"tax_rate"`
	Category    *string        `json:"category"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OrgID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.TaxRate,
		arg.Category,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE org_id = $1 AND id = $2
`

type DeleteProductParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.OrgID, arg.ID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, org_id, sku, name, description, unit_price, tax_rate, category, is_active, created_at, updated_at FROM products
WHERE org_id = $1 AND id = $2
`

type GetProductByIDParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.OrgID, arg.ID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT id, org_id, sku, name, description, unit_price, tax_rate, category, is_active, created_at, updated_at FROM products
WHERE org_id = $1 AND lower(sku) = lower($2)
`

type GetProductBySKUParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Lower string      `json:"lower"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, arg.OrgID, arg.Lower)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, org_id, sku, name, description, unit_price, tax_rate, category, is_active, created_at, updated_at FROM products
WHERE org_id = $1
  AND ($2::text IS NULL OR category = $2)
  AND ($3::boolean IS NULL OR is_active = $3)
ORDER BY created_at DESC
`

type ListProductsParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Category *string     `json:"category"`
	IsActive *bool       `json:"is_active"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.OrgID, arg.Category, arg.IsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.UnitPrice,
			&i.TaxRate,
			&i.Category,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET sku = COALESCE($1, sku),
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    unit_price = COALESCE($4, unit_price),
    tax_rate = COALESCE($5, tax_rate),
    category = COALESCE($6, category),
    is_active = COALESCE($7, is_active),
    updated_at = now()
WHERE org_id = $8 AND id = $9
RETURNING id, org_id, sku, name, description, unit_price, tax_rate, category, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	Sku         *string        `json:"sku"`
	Name        *string        `json:"name"`
	Description *string        `json:"description"`
	UnitPrice   pgtype.Numeric `json:"unit_price"`
	TaxRate     pgtype.Numeric `json:"tax_rate"`
	Category    *string        `json:"category"`
	IsActive    *bool          `json:"is_active"`
	OrgID       pgtype.UUID    `json:"org_id"`
	ID          pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.UnitPrice,
		arg.TaxRate,
		arg.Category,
		arg.IsActive,
		arg.OrgID,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.UnitPrice,
		&i.TaxRate,
		&i.Category,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
