// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package leadsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimLeadForConversion = `-- name: ClaimLeadForConversion :one
UPDATE leads
SET stage = 'converted', converted_at = now(), updated_at = now()
WHERE org_id = $1 AND id = $2 AND converted_at IS NULL
RETURNING first_name, last_name, email, phone, company, value, owner_user_id
`

type ClaimLeadForConversionParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type ClaimLeadForConversionRow struct {
	FirstName   *string        `json:"first_name"`
	LastName    *string        `json:"last_name"`
	Email       *string        `json:"email"`
	Phone       *string        `json:"phone"`
	Company     *string        `json:"company"`
	Value       pgtype.Numeric `json:"value"`
	OwnerUserID pgtype.UUID    `json:"owner_user_id"`
}

func (q *Queries) ClaimLeadForConversion(ctx context.Context, arg ClaimLeadForConversionParams) (ClaimLeadForConversionRow, error) {
	row := q.db.QueryRow(ctx, claimLeadForConversion, arg.OrgID, arg.ID)
	var i ClaimLeadForConversionRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Company,
		&i.Value,
		&i.OwnerUserID,
	)
	return i, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (
    org_id, first_name, last_name, email, phone, company, title, linkedin_url,
    source, notes, value, stage, owner_user_id, contact_id, account_id, follow_up_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
RETURNING id
`

type CreateLeadParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	FirstName   *string            `json:"first_name"`
	LastName    *string            `json:"last_name"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Company     *string            `json:"company"`
	Title       *string            `json:"title"`
	LinkedinUrl *string            `json:"linkedin_url"`
	Source      *string            `json:"source"`
	Notes       *string            `json:"notes"`
	Value       pgtype.Numeric     `json:"value"`
	Stage       string             `json:"stage"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	FollowUpAt  pgtype.Timestamptz `json:"follow_up_at"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.OrgID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Company,
		arg.Title,
		arg.LinkedinUrl,
		arg.Source,
		arg.Notes,
		arg.Value,
		arg.Stage,
		arg.OwnerUserID,
		arg.ContactID,
		arg.AccountID,
		arg.FollowUpAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteLead = `-- name: DeleteLead :execrows
DELETE FROM leads WHERE org_id = $1 AND id = $2
`

type DeleteLeadParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteLead(ctx context.Context, arg DeleteLeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLead, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLead = `-- name: GetLead :one
SELECT l.id, l.org_id, l.account_id, l.company_id, l.contact_id, l.title, l.first_name, l.last_name, l.company, l.contact_name, l.job_title, l.email, l.phone, l.linkedin_url, l.industry, l.location, l.product_interest, l.source, l.status, l.stage, l.assigned_to, l.owner_user_id, l.value_estimate, l.value, l.next_follow_up_date, l.follow_up_at, l.notes, l.converted_at, l.converted_deal_id, l.converted_contact_id, l.deleted_at, l.archived_at, l.created_at, l.updated_at, u.name AS owner_name, u.email AS owner_email
FROM leads l
LEFT JOIN users u ON u.id = l.owner_user_id
WHERE l.org_id = $1 AND l.id = $2
`

type GetLeadParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

type GetLeadRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	CompanyID          pgtype.UUID        `json:"company_id"`
	ContactID          pgtype.UUID        `json:"contact_id"`
	Title              *string            `json:"title"`
	FirstName          *string            `json:"first_name"`
	LastName           *string            `json:"last_name"`
	Company            *string            `json:"company"`
	ContactName        *string            `json:"contact_name"`
	JobTitle           *string            `json:"job_title"`
	Email              *string            `json:"email"`
	Phone              *string            `json:"phone"`
	LinkedinUrl        *string            `json:"linkedin_url"`
	Industry           *string            `json:"industry"`
	Location           *string            `json:"location"`
	ProductInterest    *string            `json:"product_interest"`
	Source             *string            `json:"source"`
	Status             string             `json:"status"`
	Stage              string             `json:"stage"`
	AssignedTo         pgtype.UUID        `json:"assigned_to"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	ValueEstimate      pgtype.Numeric     `json:"value_estimate"`
	Value              pgtype.Numeric     `json:"value"`
	NextFollowUpDate   pgtype.Date        `json:"next_follow_up_date"`
	FollowUpAt         pgtype.Timestamptz `json:"follow_up_at"`
	Notes              *string            `json:"notes"`
	ConvertedAt        pgtype.Timestamptz `json:"converted_at"`
	ConvertedDealID    pgtype.UUID        `json:"converted_deal_id"`
	ConvertedContactID pgtype.UUID        `json:"converted_contact_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	OwnerName          *string            `json:"owner_name"`
	OwnerEmail         *string            `json:"owner_email"`
}

func (q *Queries) GetLead(ctx context.Context, arg GetLeadParams) (GetLeadRow, error) {
	row := q.db.QueryRow(ctx, getLead, arg.OrgID, arg.ID)
	var i GetLeadRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AccountID,
		&i.CompanyID,
		&i.ContactID,
		&i.Title,
		&i.FirstName,
		&i.LastName,
		&i.Company,
		&i.ContactName,
		&i.JobTitle,
		&i.Email,
		&i.Phone,
		&i.LinkedinUrl,
		&i.Industry,
		&i.Location,
		&i.ProductInterest,
		&i.Source,
		&i.Status,
		&i.Stage,
		&i.AssignedTo,
		&i.OwnerUserID,
		&i.ValueEstimate,
		&i.Value,
		&i.NextFollowUpDate,
		&i.FollowUpAt,
		&i.Notes,
		&i.ConvertedAt,
		&i.ConvertedDealID,
		&i.ConvertedContactID,
		&i.DeletedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerName,
		&i.OwnerEmail,
	)
	return i, err
}

const leadStats = `-- name: LeadStats :many
SELECT stage, count(*), COALESCE(sum(value), 0)::float8
FROM leads WHERE org_id = $1 GROUP BY stage
`

type LeadStatsRow struct {
	Stage   string  `json:"stage"`
	Count   int64   `json:"count"`
	Column3 float64 `json:"column_3"`
}

func (q *Queries) LeadStats(ctx context.Context, orgID pgtype.UUID) ([]LeadStatsRow, error) {
	rows, err := q.db.Query(ctx, leadStats, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeadStatsRow
	for rows.Next() {
		var i LeadStatsRow
		if err := rows.Scan(&i.Stage, &i.Count, &i.Column3); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkConversion = `-- name: LinkConversion :exec
UPDATE leads SET converted_deal_id = $3, converted_contact_id = $4
WHERE org_id = $1 AND id = $2
`

type LinkConversionParams struct {
	OrgID              pgtype.UUID `json:"org_id"`
	ID                 pgtype.UUID `json:"id"`
	ConvertedDealID    pgtype.UUID `json:"converted_deal_id"`
	ConvertedContactID pgtype.UUID `json:"converted_contact_id"`
}

func (q *Queries) LinkConversion(ctx context.Context, arg LinkConversionParams) error {
	_, err := q.db.Exec(ctx, linkConversion,
		arg.OrgID,
		arg.ID,
		arg.ConvertedDealID,
		arg.ConvertedContactID,
	)
	return err
}

const listLeadsBoard = `-- name: ListLeadsBoard :many

SELECT l.id, l.org_id, l.account_id, l.company_id, l.contact_id, l.title, l.first_name, l.last_name, l.company, l.contact_name, l.job_title, l.email, l.phone, l.linkedin_url, l.industry, l.location, l.product_interest, l.source, l.status, l.stage, l.assigned_to, l.owner_user_id, l.value_estimate, l.value, l.next_follow_up_date, l.follow_up_at, l.notes, l.converted_at, l.converted_deal_id, l.converted_contact_id, l.deleted_at, l.archived_at, l.created_at, l.updated_at, u.name AS owner_name, u.email AS owner_email
FROM leads l
LEFT JOIN users u ON u.id = l.owner_user_id
WHERE l.org_id = $1
ORDER BY l.stage, l.created_at DESC, l.id
LIMIT $2
`

type ListLeadsBoardParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	Limit int32       `json:"limit"`
}

type ListLeadsBoardRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	CompanyID          pgtype.UUID        `json:"company_id"`
	ContactID          pgtype.UUID        `json:"contact_id"`
	Title              *string            `json:"title"`
	FirstName          *string            `json:"first_name"`
	LastName           *string            `json:"last_name"`
	Company            *string            `json:"company"`
	ContactName        *string            `json:"contact_name"`
	JobTitle           *string            `json:"job_title"`
	Email              *string            `json:"email"`
	Phone              *string            `json:"phone"`
	LinkedinUrl        *string            `json:"linkedin_url"`
	Industry           *string            `json:"industry"`
	Location           *string            `json:"location"`
	ProductInterest    *string            `json:"product_interest"`
	Source             *string            `json:"source"`
	Status             string             `json:"status"`
	Stage              string             `json:"stage"`
	AssignedTo         pgtype.UUID        `json:"assigned_to"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	ValueEstimate      pgtype.Numeric     `json:"value_estimate"`
	Value              pgtype.Numeric     `json:"value"`
	NextFollowUpDate   pgtype.Date        `json:"next_follow_up_date"`
	FollowUpAt         pgtype.Timestamptz `json:"follow_up_at"`
	Notes              *string            `json:"notes"`
	ConvertedAt        pgtype.Timestamptz `json:"converted_at"`
	ConvertedDealID    pgtype.UUID        `json:"converted_deal_id"`
	ConvertedContactID pgtype.UUID        `json:"converted_contact_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	OwnerName          *string            `json:"owner_name"`
	OwnerEmail         *string            `json:"owner_email"`
}

// SQL queries for leads package.
// Every statement filters on org_id to maintain tenant isolation.
func (q *Queries) ListLeadsBoard(ctx context.Context, arg ListLeadsBoardParams) ([]ListLeadsBoardRow, error) {
	rows, err := q.db.Query(ctx, listLeadsBoard, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeadsBoardRow
	for rows.Next() {
		var i ListLeadsBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AccountID,
			&i.CompanyID,
			&i.ContactID,
			&i.Title,
			&i.FirstName,
			&i.LastName,
			&i.Company,
			&i.ContactName,
			&i.JobTitle,
			&i.Email,
			&i.Phone,
			&i.LinkedinUrl,
			&i.Industry,
			&i.Location,
			&i.ProductInterest,
			&i.Source,
			&i.Status,
			&i.Stage,
			&i.AssignedTo,
			&i.OwnerUserID,
			&i.ValueEstimate,
			&i.Value,
			&i.NextFollowUpDate,
			&i.FollowUpAt,
			&i.Notes,
			&i.ConvertedAt,
			&i.ConvertedDealID,
			&i.ConvertedContactID,
			&i.DeletedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.OwnerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerInOrg = `-- name: OwnerInOrg :one
SELECT EXISTS (SELECT 1 FROM users WHERE org_id = $1 AND id = $2)
`

type OwnerInOrgParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) OwnerInOrg(ctx context.Context, arg OwnerInOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, ownerInOrg, arg.OrgID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setLeadStage = `-- name: SetLeadStage :execrows
UPDATE leads SET stage = $3, updated_at = now() WHERE org_id = $1 AND id = $2
`

type SetLeadStageParams struct {
	OrgID pgtype.UUID `json:"org_id"`
	ID    pgtype.UUID `json:"id"`
	Stage string      `json:"stage"`
}

func (q *Queries) SetLeadStage(ctx context.Context, arg SetLeadStageParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLeadStage, arg.OrgID, arg.ID, arg.Stage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLead = `-- name: UpdateLead :execrows
UPDATE leads
SET first_name = $3, last_name = $4, email = $5, phone = $6, company = $7,
    title = $8, linkedin_url = $9, source = $10, notes = $11, value = $12,
    stage = $13, owner_user_id = $14, contact_id = $15, account_id = $16,
    follow_up_at = $17, updated_at = now()
WHERE org_id = $1 AND id = $2
`

type UpdateLeadParams struct {
	OrgID       pgtype.UUID        `json:"org_id"`
	ID          pgtype.UUID        `json:"id"`
	FirstName   *string            `json:"first_name"`
	LastName    *string            `json:"last_name"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Company     *string            `json:"company"`
	Title       *string            `json:"title"`
	LinkedinUrl *string            `json:"linkedin_url"`
	Source      *string            `json:"source"`
	Notes       *string            `json:"notes"`
	Value       pgtype.Numeric     `json:"value"`
	Stage       string             `json:"stage"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	AccountID   pgtype.UUID        `json:"account_id"`
	FollowUpAt  pgtype.Timestamptz `json:"follow_up_at"`
}

func (q *Queries) UpdateLead(ctx context.Context, arg UpdateLeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLead,
		arg.OrgID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Company,
		arg.Title,
		arg.LinkedinUrl,
		arg.Source,
		arg.Notes,
		arg.Value,
		arg.Stage,
		arg.OwnerUserID,
		arg.ContactID,
		arg.AccountID,
		arg.FollowUpAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
