// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package integrationsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integration_connections
WHERE org_id = $1 AND provider = $2
`

type DeleteIntegrationParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) error {
	_, err := q.db.Exec(ctx, deleteIntegration, arg.OrgID, arg.Provider)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, org_id, provider, encrypted_tokens, metadata, created_at, updated_at FROM integration_connections
WHERE org_id = $1 AND provider = $2
`

type GetIntegrationParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	Provider string      `json:"provider"`
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (IntegrationConnection, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.OrgID, arg.Provider)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.EncryptedTokens,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSlackChannel = `-- name: GetSlackChannel :one
SELECT id, org_id, entity_type, entity_id, channel_id, created_at FROM slack_channels
WHERE org_id = $1 AND entity_type = $2 AND entity_id = $3
`

type GetSlackChannelParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) GetSlackChannel(ctx context.Context, arg GetSlackChannelParams) (SlackChannel, error) {
	row := q.db.QueryRow(ctx, getSlackChannel, arg.OrgID, arg.EntityType, arg.EntityID)
	var i SlackChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EntityType,
		&i.EntityID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const mapSlackChannel = `-- name: MapSlackChannel :one
INSERT INTO slack_channels (
    org_id, entity_type, entity_id, channel_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, org_id, entity_type, entity_id, channel_id, created_at
`

type MapSlackChannelParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	ChannelID  string      `json:"channel_id"`
}

func (q *Queries) MapSlackChannel(ctx context.Context, arg MapSlackChannelParams) (SlackChannel, error) {
	row := q.db.QueryRow(ctx, mapSlackChannel,
		arg.OrgID,
		arg.EntityType,
		arg.EntityID,
		arg.ChannelID,
	)
	var i SlackChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.EntityType,
		&i.EntityID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertIntegration = `-- name: UpsertIntegration :one
INSERT INTO integration_connections (
    org_id, provider, encrypted_tokens, metadata
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (org_id, provider) DO UPDATE
SET encrypted_tokens = EXCLUDED.encrypted_tokens,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, org_id, provider, encrypted_tokens, metadata, created_at, updated_at
`

type UpsertIntegrationParams struct {
	OrgID           pgtype.UUID `json:"org_id"`
	Provider        string      `json:"provider"`
	EncryptedTokens []byte      `json:"encrypted_tokens"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (IntegrationConnection, error) {
	row := q.db.QueryRow(ctx, upsertIntegration,
		arg.OrgID,
		arg.Provider,
		arg.EncryptedTokens,
		arg.Metadata,
	)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Provider,
		&i.EncryptedTokens,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
