// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Website     *string            `json:"website"`
	Industry    *string            `json:"industry"`
	Phone       *string            `json:"phone"`
	Notes       *string            `json:"notes"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Activity struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Type       string             `json:"type"`
	AuthorID   pgtype.UUID        `json:"author_id"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	DealID     pgtype.UUID        `json:"deal_id"`
	Body       string             `json:"body"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	IpAddress  *string            `json:"ip_address"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Changes    []byte             `json:"changes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CalendarEvent struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	LeadID        pgtype.UUID        `json:"lead_id"`
	GoogleEventID string             `json:"google_event_id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	StartAt       pgtype.Timestamptz `json:"start_at"`
	EndAt         pgtype.Timestamptz `json:"end_at"`
	MeetLink      *string            `json:"meet_link"`
	CreatedBy     pgtype.UUID        `json:"created_by"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Company struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Name       string             `json:"name"`
	Domain     *string            `json:"domain"`
	Industry   *string            `json:"industry"`
	City       *string            `json:"city"`
	Website    *string            `json:"website"`
	Source     *string            `json:"source"`
	Tags       []string           `json:"tags"`
	LogoPath   *string            `json:"logo_path"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Contact struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	CompanyID  pgtype.UUID        `json:"company_id"`
	AccountID  pgtype.UUID        `json:"account_id"`
	FirstName  string             `json:"first_name"`
	LastName   *string            `json:"last_name"`
	Email      *string            `json:"email"`
	Phone      *string            `json:"phone"`
	Title      *string            `json:"title"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Deal struct {
	ID                     pgtype.UUID        `json:"id"`
	OrgID                  pgtype.UUID        `json:"org_id"`
	Title                  string             `json:"title"`
	JobTitle               *string            `json:"job_title"`
	CompanyID              pgtype.UUID        `json:"company_id"`
	AccountID              pgtype.UUID        `json:"account_id"`
	ContactID              pgtype.UUID        `json:"contact_id"`
	PrimaryContactID       pgtype.UUID        `json:"primary_contact_id"`
	LeadID                 pgtype.UUID        `json:"lead_id"`
	Stage                  string             `json:"stage"`
	Position               int32              `json:"position"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Description            *string            `json:"description"`
	ProductUseCase         *string            `json:"product_use_case"`
	Probability            *int32             `json:"probability"`
	NextAction             *string            `json:"next_action"`
	SiteAssessmentDate     pgtype.Date        `json:"site_assessment_date"`
	SiteAssessmentLocation *string            `json:"site_assessment_location"`
	SiteAssessmentNotes    *string            `json:"site_assessment_notes"`
	LostReason             *string            `json:"lost_reason"`
	Notes                  *string            `json:"notes"`
	OwnerID                pgtype.UUID        `json:"owner_id"`
	OwnerUserID            pgtype.UUID        `json:"owner_user_id"`
	ExpectedCloseDate      pgtype.Date        `json:"expected_close_date"`
	DeletedAt              pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type FollowUp struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	InvoiceID     pgtype.UUID        `json:"invoice_id"`
	LeadID        pgtype.UUID        `json:"lead_id"`
	DealID        pgtype.UUID        `json:"deal_id"`
	AssignedTo    pgtype.UUID        `json:"assigned_to"`
	Title         string             `json:"title"`
	ScheduledFor  pgtype.Timestamptz `json:"scheduled_for"`
	DueAt         pgtype.Timestamptz `json:"due_at"`
	Channel       *string            `json:"channel"`
	Status        string             `json:"status"`
	AttemptNumber int32              `json:"attempt_number"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationConnection struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Provider          string             `json:"provider"`
	AccessToken       string             `json:"access_token"`
	RefreshToken      *string            `json:"refresh_token"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Scope             *string            `json:"scope"`
	ProviderAccountID *string            `json:"provider_account_id"`
	EncryptedTokens   *string            `json:"encrypted_tokens"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Invitation struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Email      string             `json:"email"`
	TokenHash  string             `json:"token_hash"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	QuoteID          pgtype.UUID        `json:"quote_id"`
	CompanyID        pgtype.UUID        `json:"company_id"`
	AccountID        pgtype.UUID        `json:"account_id"`
	ContactID        pgtype.UUID        `json:"contact_id"`
	DealID           pgtype.UUID        `json:"deal_id"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Number           *string            `json:"number"`
	InvoiceNumber    *string            `json:"invoice_number"`
	Title            *string            `json:"title"`
	Status           string             `json:"status"`
	AmountDue        pgtype.Numeric     `json:"amount_due"`
	Currency         string             `json:"currency"`
	IssueDate        pgtype.Date        `json:"issue_date"`
	DueDate          pgtype.Date        `json:"due_date"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountTotal    pgtype.Numeric     `json:"discount_total"`
	TaxTotal         pgtype.Numeric     `json:"tax_total"`
	Total            pgtype.Numeric     `json:"total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	StripeInvoiceID  *string            `json:"stripe_invoice_id"`
	PaymentLink      *string            `json:"payment_link"`
	SourceQuoteID    *string            `json:"source_quote_id"`
	AccountManagerID pgtype.UUID        `json:"account_manager_id"`
	SentAt           pgtype.Timestamptz `json:"sent_at"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	VoidedAt         pgtype.Timestamptz `json:"voided_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type InvoiceItem struct {
	ID              pgtype.UUID    `json:"id"`
	InvoiceID       pgtype.UUID    `json:"invoice_id"`
	OrgID           pgtype.UUID    `json:"org_id"`
	Position        int32          `json:"position"`
	Description     string         `json:"description"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	DiscountPercent pgtype.Numeric `json:"discount_percent"`
	TaxPercent      pgtype.Numeric `json:"tax_percent"`
	LineTotal       pgtype.Numeric `json:"line_total"`
}

type Lead struct {
	ID                 pgtype.UUID        `json:"id"`
	OrgID              pgtype.UUID        `json:"org_id"`
	AccountID          pgtype.UUID        `json:"account_id"`
	CompanyID          pgtype.UUID        `json:"company_id"`
	ContactID          pgtype.UUID        `json:"contact_id"`
	Title              *string            `json:"title"`
	FirstName          *string            `json:"first_name"`
	LastName           *string            `json:"last_name"`
	Company            *string            `json:"company"`
	ContactName        *string            `json:"contact_name"`
	JobTitle           *string            `json:"job_title"`
	Email              *string            `json:"email"`
	Phone              *string            `json:"phone"`
	LinkedinUrl        *string            `json:"linkedin_url"`
	Industry           *string            `json:"industry"`
	Location           *string            `json:"location"`
	ProductInterest    *string            `json:"product_interest"`
	Source             *string            `json:"source"`
	Status             string             `json:"status"`
	Stage              string             `json:"stage"`
	AssignedTo         pgtype.UUID        `json:"assigned_to"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	ValueEstimate      pgtype.Numeric     `json:"value_estimate"`
	Value              pgtype.Numeric     `json:"value"`
	NextFollowUpDate   pgtype.Date        `json:"next_follow_up_date"`
	FollowUpAt         pgtype.Timestamptz `json:"follow_up_at"`
	Notes              *string            `json:"notes"`
	ConvertedAt        pgtype.Timestamptz `json:"converted_at"`
	ConvertedDealID    pgtype.UUID        `json:"converted_deal_id"`
	ConvertedContactID pgtype.UUID        `json:"converted_contact_id"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt         pgtype.Timestamptz `json:"archived_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Organization struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Currency   string             `json:"currency"`
	QuoteSeq   int32              `json:"quote_seq"`
	InvoiceSeq int32              `json:"invoice_seq"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                    pgtype.UUID        `json:"id"`
	OrgID                 pgtype.UUID        `json:"org_id"`
	InvoiceID             pgtype.UUID        `json:"invoice_id"`
	Amount                pgtype.Numeric     `json:"amount"`
	Currency              string             `json:"currency"`
	StripePaymentIntentID *string            `json:"stripe_payment_intent_id"`
	Status                string             `json:"status"`
	PaidOn                pgtype.Date        `json:"paid_on"`
	PaidAt                pgtype.Timestamptz `json:"paid_at"`
	Method                *string            `json:"method"`
	Reference             *string            `json:"reference"`
	Note                  *string            `json:"note"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	Name        string             `json:"name"`
	Sku         string             `json:"sku"`
	Category    *string            `json:"category"`
	Description *string            `json:"description"`
	UnitPrice   pgtype.Numeric     `json:"unit_price"`
	Currency    string             `json:"currency"`
	TaxRate     pgtype.Numeric     `json:"tax_rate"`
	Active      bool               `json:"active"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	AvatarUrl *string            `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Quote struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Number         *string            `json:"number"`
	DealID         pgtype.UUID        `json:"deal_id"`
	CompanyID      pgtype.UUID        `json:"company_id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	ContactID      pgtype.UUID        `json:"contact_id"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	Status         string             `json:"status"`
	CurrentVersion int32              `json:"current_version"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	ValidUntil     pgtype.Date        `json:"valid_until"`
	Currency       string             `json:"currency"`
	Subtotal       pgtype.Numeric     `json:"subtotal"`
	DiscountTotal  pgtype.Numeric     `json:"discount_total"`
	TaxTotal       pgtype.Numeric     `json:"tax_total"`
	Total          pgtype.Numeric     `json:"total"`
	Notes          *string            `json:"notes"`
	SentAt         pgtype.Timestamptz `json:"sent_at"`
	AcceptedAt     pgtype.Timestamptz `json:"accepted_at"`
	DeclinedAt     pgtype.Timestamptz `json:"declined_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuoteApproval struct {
	ID              pgtype.UUID        `json:"id"`
	QuoteVersionID  pgtype.UUID        `json:"quote_version_id"`
	MagicLinkToken  string             `json:"magic_link_token"`
	ApprovedByName  *string            `json:"approved_by_name"`
	ApprovedByEmail *string            `json:"approved_by_email"`
	SignatureData   *string            `json:"signature_data"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	IpAddress       *string            `json:"ip_address"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type QuoteItem struct {
	ID              pgtype.UUID    `json:"id"`
	QuoteID         pgtype.UUID    `json:"quote_id"`
	OrgID           pgtype.UUID    `json:"org_id"`
	Position        int32          `json:"position"`
	Description     string         `json:"description"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	DiscountPercent pgtype.Numeric `json:"discount_percent"`
	TaxPercent      pgtype.Numeric `json:"tax_percent"`
	LineTotal       pgtype.Numeric `json:"line_total"`
}

type QuoteVersion struct {
	ID            pgtype.UUID        `json:"id"`
	QuoteID       pgtype.UUID        `json:"quote_id"`
	VersionNumber int32              `json:"version_number"`
	LineItems     []byte             `json:"line_items"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	Tax           pgtype.Numeric     `json:"tax"`
	Total         pgtype.Numeric     `json:"total"`
	Currency      string             `json:"currency"`
	PdfPath       *string            `json:"pdf_path"`
	IsCurrent     bool               `json:"is_current"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type SlackChannel struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	DealID         pgtype.UUID        `json:"deal_id"`
	EntityType     *string            `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	ChannelID      *string            `json:"channel_id"`
	SlackChannelID *string            `json:"slack_channel_id"`
	ChannelName    string             `json:"channel_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Email          string             `json:"email"`
	PasswordHash   *string            `json:"password_hash"`
	AuthProvider   string             `json:"auth_provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	Name           *string            `json:"name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
