// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package authdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateOrganization(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createOrganization, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, org_id, password_hash, auth_provider, provider_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, org_id, password_hash, auth_provider, provider_user_id, created_at
`

type CreateUserParams struct {
	Email          string      `json:"email"`
	OrgID          pgtype.UUID `json:"org_id"`
	PasswordHash   *string     `json:"password_hash"`
	AuthProvider   string      `json:"auth_provider"`
	ProviderUserID *string     `json:"provider_user_id"`
}

type CreateUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	OrgID          pgtype.UUID        `json:"org_id"`
	PasswordHash   *string            `json:"password_hash"`
	AuthProvider   string             `json:"auth_provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Runs in the same transaction as CreateOrganization: users.org_id is NOT NULL
// and a user without an organization could not reach any CRM data.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.OrgID,
		arg.PasswordHash,
		arg.AuthProvider,
		arg.ProviderUserID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrgID,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, email, org_id, password_hash, auth_provider, provider_user_id, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	OrgID          pgtype.UUID        `json:"org_id"`
	PasswordHash   *string            `json:"password_hash"`
	AuthProvider   string             `json:"auth_provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// SQL reference for the eventual sqlc migration; the module currently runs the
// hand-written pgx repository in store.go. Keep the two in sync.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrgID,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, email, org_id, password_hash, auth_provider, provider_user_id, created_at
FROM users
WHERE auth_provider = $1 AND provider_user_id = $2
`

type GetUserByProviderParams struct {
	AuthProvider   string  `json:"auth_provider"`
	ProviderUserID *string `json:"provider_user_id"`
}

type GetUserByProviderRow struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	OrgID          pgtype.UUID        `json:"org_id"`
	PasswordHash   *string            `json:"password_hash"`
	AuthProvider   string             `json:"auth_provider"`
	ProviderUserID *string            `json:"provider_user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (GetUserByProviderRow, error) {
	row := q.db.QueryRow(ctx, getUserByProvider, arg.AuthProvider, arg.ProviderUserID)
	var i GetUserByProviderRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrgID,
		&i.PasswordHash,
		&i.AuthProvider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}
